### ISSUE TITLE
Running failure

### ISSUE THREAD

**Issue by damianfreilij** [emmanuelparadis/coalescentMCMC#1]
I am having a problem with the execution of the data. I'm working with 331 sequences of 575 bp (file named secfas, a dnabin), and when I try to run the coalescentMCMC function, regardless of the model, it doesn't run. 

outc <- coalescentMCMC(secfas, ntrees = 1000,model = "constant",tree0 = NULL)
outexp <- coalescentMCMC(secfas, ntrees = 1000, model = "time")
outstep <- coalescentMCMC(secfas, ntrees = 1000, model = "step")
outlin <- coalescentMCMC(secfas, ntrees = 1000, model = "linear")

It starts with this message, normally:

Running the Markov chain:
Number of generations to run: 1000 
Generation Nb of accepted moves

Sometimes, after a while R aborts the session, or nothing happens. At first I thought it was because of the capacity of my computer, but I have tried on computers with more processing, and nothing, not even when trying to run 10 trees. I would like to know if there is a maximum number of sequences the package can work with.

Thank you very much, best regards,

**Comment by emmanuelparadis** [comment]
I suggest you try this command:
```r
out <- coalescentMCMC(secfas, printevery = 1, moves = c(1, 6))
```

**Comment by damianfreilij** [comment]
Dear Emmanuel

The issue has been fixed with that command.

Thank you very much!
